fixtures:
  repositories:
    apt:        "https://github.com/puppetlabs/puppetlabs-apt.git"
    chocolatey: "https://github.com/puppetlabs/puppetlabs-chocolatey.git"
    concat:     "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib:     "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  forge_modules:
    zypprepo: "darin/zypprepo"
  symlinks:
    icinga2: "#{source_dir}"
