fixtures:
  repositories:
    icinga:
      repo: https://github.com/SimonHoenscheid/puppet-icinga.git
      branch: simonhoenscheid_activate_epel_on_fedora_hard_dependency_icinga2_module
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    concat:
      repo: puppetlabs/concat
    apt:
      repo: puppetlabs/apt
    chocolatey:
      repo: puppetlabs/chocolatey
    zypprepo:
      repo: puppet/zypprepo
    yumrepo_core:
      repo: puppetlabs-yumrepo_core
      puppet_version: ">= 6.0.0"

